config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :scenarios do
    resources :scenes
  end
  root 'scenarios#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scenario.rb
class Scenario < ApplicationRecord
    belongs_to :user
    has_many :scenes, dependent: :destroy
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :scenario
  validates :description, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :scenarios 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only:
  [:new, :create, :update, :edit, :destroy]

  # GET /scenarios or /scenarios.json
  def index
    @scenarios = Scenario.all
  end

  # GET /scenarios/1 or /scenarios/1.json
  def show
    @user = @scenario.user
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios or /scenarios.json
  def create
    @scenario = Scenario.new(scenario_params)
    @scenario.user = current_user

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: "Scenario was successfully created." }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1 or /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: "Scenario was successfully updated." }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1 or /scenarios/1.json
  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html { redirect_to scenarios_url, notice: "Scenario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scenario_params
      params.require(:scenario).permit(:title, :image, :description, :start, :end)
    end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :get_scenario
  before_action :set_scene, only: %i[ show edit update destroy ]
  
  # GET /scenes or /scenes.json
  def index
    @scenes = @scenario.scenes
  end

  # GET /scenes/1 or /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = @scenario.scenes.build
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes or /scenes.json
  def create
    @scene = @scenario.scenes.build(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to scenario_scenes_path(@scenario), notice: "Scene was successfully created." }
        format.json { render :show, status: :created, location: @scene }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1 or /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to scenario_scenes_path(@scenario), notice: "Scene was successfully updated." }
        format.json { render :show, status: :ok, location: @scene }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1 or /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenario_scenes_path(@scenario), notice: "Scene was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def get_scenario
    @scenario = Scenario.find(params[:scenario_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = @scenario.scenes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scene_params
      params.require(:scene).permit(:title, :image, :number, :description, :when, :scenario_id)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/layouts/_devise_links.html.erb
<br>
<% if user_signed_in? %>
  
  </br>
  <button class="btn bg-light text-dark" type="submit"><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </button>
         
  
  </br>
  </br>
  </div>
<% else %>
  
  
  <button class="btn bg-light text-dark" type="submit"><%= link_to('Login', new_user_session_path) %>  </button>
  </br>
  </br>
  
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BigPicture</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/devise_links'%>
  </body>
</html>

app/views/scenarios/_form.html.erb
<%= form_with(model: scenario) do |form| %>
  <% if scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
        <% scenario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form class="row g-3 needs-validation" novalidate>
    <div class="form-group mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "title" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :image, class: "form-label" %>
      <%= form.text_field :image, class: "form-control", placeholder: "web-link to an image" %>
    </div>

    <div class="form-group mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", placeholder: "synopsis of your scenario" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :start, class: "form-label" %>
      <%= form.date_select :start%>
    </div>

    <div class="form-group mb-3">
      <%= form.label :end, class: "form-label" %>
      <%= form.date_select :end %>
    </div>
    </br>
    <div class="actions">
    <button class="btn bg-light text-dark" type="submit">Submit form</button>
    </div>
  </form>
<% end %>

app/views/scenarios/edit.html.erb
<h1>Editing Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scenarios</h1>

<table class="table table-dark table-striped table-borderless ">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Description</th>
      <th>Start</th>
      <th>End</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= scenario.title %></td>
        <td><img src="<%= scenario.image %>" class="img-thumbnail" alt="img-scene"></td>
        <td><%= scenario.description %></td>
        <td><%= scenario.start %></td>
        <td><%= scenario.end %></td>
        <td><% if scenario.user.present? %>
        <%= scenario.user.email %>
        <% end %></td>
        <td><button type="button" class="btn bg-light text-dark"><%= link_to 'Show', scenario %></button></td>
        <td><button type="button" class="btn bg-secondary"><%= link_to 'Edit', edit_scenario_path(scenario) %></button></td>
        <td><button type="button" class="btn bg-danger"><%= link_to 'Destroy', scenario, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn bg-light text-dark"><%= link_to 'New Scenario', new_scenario_path %></button>

app/views/scenarios/new.html.erb
<h1>New Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Back', scenarios_path %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card" style="width: 18rem;">
  <img src="<%= @scenario.image %>" class="card-img-top img-thumbnail" alt="img-scenario">
  <div class="card-body">
    <h5 class="card-title"><strong>Title:</strong><%= @scenario.title %></h5>
    <p class="card-text"><strong>Description:</strong><%= @scenario.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Start:</strong>
    <%= @scenario.start %></li>
    <li class="list-group-item"><strong>End:</strong>
    <%= @scenario.end %></li>
    <li class="list-group-item"><strong>Author:</strong>
    <%= @user.email %></li>
  </ul>
  <div class="card-body">
  <button type="button" class="btn bg-dark"><%= link_to 'Edit Scenario', edit_scenario_path(@scenario) %> </button> |
  <button type="button" class="btn bg-dark"><%= link_to 'Back', scenarios_path %></button>
  </div>
</div>
</br></br>




  

<div>
</br>
<h2>Scene :</h2>
</br>

<table class="table table-dark table-striped table-borderless ">
  <thead >
    <tr>
      <th >Scene Title</th>
      <th>Image</th>
      <th>Number</th>
      <th>Description</th>
      <th>Date</th>
      <th>Scenario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
  <% for scene in @scenario.scenes %>
      <tr>
        <td><%= scene.title %></td>
        <td><img src="<%= scene.image %>" class="img-thumbnail" alt="img-scene" ></td>
        <td><%= scene.number %></td>
        <td><%= scene.description %></td>
        <td><%= scene.when %></td>
        <td><%= scene.scenario.title %></td>
        <td><%= link_to 'Edit Scene', edit_scenario_scene_path(@scenario, scene) %></td>
        <td><%= link_to 'Destroy Scene', [@scenario, scene], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<button type="button" class="btn bg-light text-dark"><%= link_to 'Add Scene', new_scenario_scene_path(@scenario) %></button>

<br>

app/views/scenes/_form.html.erb
<%= form_with(model: [@scenario, scene]) do |form| %>
  <% if scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
        <% scene.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form class="row g-3 needs-validation" novalidate>
    <div class="form-group mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "title" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :image, class: "form-label" %>
      <%= form.text_field :image, class: "form-control", placeholder: "web-link to an image" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :number, class: "form-label" %>
      <%= form.text_field :number, class: "form-control", placeholder: "the order of the scene" %>
    </div>


    <div class="form-group mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", placeholder: "your scene" %>
    </div>

    <div class="form-group mb-3">
    <%= form.label :when, class: "form-label"  %>
    <%= form.date_select :when %>
  </div>



  <div class="actions">
    <button class="btn btn-primary" type="submit">Submit form</button>
    </div>
  </form>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Show', [@scenario, @scene] %> |
<%= link_to 'Back', scenario_scenes_path(@scenario) %>

app/views/scenes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-responsive">
<h1>Scenes</h1>
</br>

<table class="table table-dark table-striped table-borderless ">
  <thead >
    <tr>
      <th >Scene Title</th>
      <th>Image</th>
      <th>Number</th>
      <th>Description</th>
      <th>Date</th>
      <th>Scenario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @scenes.each do |scene| %>
      <tr>
        <td><%= scene.title %></td>
        <td><img src="<%= scene.image %>" class="img-thumbnail" alt="img-scene" ></td>
        <td><%= scene.number %></td>
        <td><%= scene.description %></td>
        <td><%= scene.when %></td>
        <td><%= scene.scenario.title %></td>
        
        
        
        <td><button type="button" class="btn bg-secondary"><%= link_to 'Edit Scene', edit_scenario_scene_path(@scenario, scene) %></button></td>
        <td><button type="button" class="btn bg-danger"><%= link_to 'Destroy Scene', [@scenario, scene], method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn bg-light text-dark"><%= link_to 'New Scene', new_scenario_scene_path(@scenario) %></button> |
</br></br>
<button type="button" class="btn bg-light text-dark"><%= link_to 'Back', [@scenario] %></button>

app/views/scenes/new.html.erb
<h1>New Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Back', [@scenario] %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scene.title %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%= scene.image %>" class="img-thumbnail" alt="img-scene" >
  </p>

<p>
  <strong>Number:</strong>
  <%= @scene.number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scene.description %>
</p>

<p>
  <strong>When:</strong>
  <%= @scene.when %>
</p>

<p>
  <strong>Scenario:</strong>
  <%= @scene.scenario_id %>
</p>

<%= link_to 'Edit', edit_scenario_scene_path(@scenario, @scene) %> |
<%= link_to 'Back', scenario_scenes_path(@scenario) %>